### ISSUE TITLE
Add API

### ISSUE THREAD

**Issue by JMixson** [btoch23/circuit-creator#1]
Replace data with data from API.

Possible APIs:
* https://wger.de/en/software/api (has more content like images)
* https://api-ninjas.com/api/exercises (cleaner data; might be easier to implement)

**Comment by btoch23** [comment]
@martinvanalli @DanScheuerman @JMixson 

I've incorporated the API Ninjas API so users can select a muscle and get exercises for that muscle. Haven't been able to fix the functionality to remove exercises from the list and have the buttons update. Also, if a user selects the max number of exercises and then clicks a new muscle group, they're able to add more exercises than they should. Not sure how to fix that.

**Comment by btoch23** [comment]
@JMixson @martinvanalli @DanScheuerman 

if we could also figure out how to make the instructions collapsible somehow so they don't take up so much room by default that'd be great too.

**Comment by DanScheuerman** [comment]
Cool I'll have a look at making the instructions collapsible
